name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_11.3.app/Contents/Developer'
    - name: Run tests
      run: xcodebuild
            -list
            -scheme ncmb_swift
            -sdk iphonesimulator
            -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max'
            clean test
